# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: AzureAppServiceManage@0
  displayName: "Stopping App Service (Production)"
  inputs:
    azureSubscription: "AzureDevOpsConnection"
    Action: "Stop Azure App Service"
    WebAppName: 'diocamStopSlot'

- task: AzureAppServiceManage@0
  displayName: "Stopping App Service Slot"
  inputs:
    azureSubscription: "AzureDevOpsConnection"
    Action: "Stop Azure App Service"
    WebAppName: 'diocamStopSlot'
    SpecifySlotOrASE: true
    Slot: 'deploy'
