# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AzureAppServiceManage@0
  displayName: "Stopping App Service (Production)"
  inputs:
    azureSubscription: "diocamStopSlot"
    Action: "Stop Azure App Service"
    WebAppName: 'diocamStopSlot'

- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: $(System.DefaultWorkingDirectory)\test1.ps1
  displayName: 'Print Hello World'

#- task: AzureAppServiceManage@0
 # displayName: "Stopping App Service Slot"
 # inputs:
 #   azureSubscription: "diocamStopSlot"
  #  Action: "Stop Azure App Service"
  #  WebAppName: 'diocamstopslot/mytest'
  #  SpecifySlotOrASE: true
  #  Slot: 'mytest'
    
