# ASP.NET Core
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'MAIC - TEK Experts CR - v-juasol Group#1 (90d7af21-b3a1-4bf8-a149-8e1fcc47e337)'
    appType: 'webApp'
    WebAppName: 'diocamStopSlot'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: AzureAppServiceManage@0
  displayName: "Stopping App Service (Production)"
  inputs:
    azureSubscription: "AzureDevOpsConnection"
    Action: "Stop Azure App Service"
    WebAppName: 'diocamStopSlot'

- task: AzureAppServiceManage@0
  displayName: "Stopping App Service Slot"
  inputs:
    azureSubscription: "AzureDevOpsConnection"
    Action: "Stop Azure App Service"
    WebAppName: 'diocamStopSlot'
    SpecifySlotOrASE: true
    Slot: 'deploy'
